name: Java CI/CD with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Run tests
        run: mvn -B test --file pom.xml

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Rename JAR
        run: |
          FILE=$(ls target/*-shaded.jar | head -n 1)
          cp "$FILE" target/tic-tac-toe-latest.jar

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: TicTacToe-jar
          path: target/tic-tac-toe-latest.jar

      - name: Deploy JAR to GitHub Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Release
          files: target/tic-tac-toe-latest.jar
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
